tasks:
  - name: Shopware
    init: |
      docker run -d --name=mysql -p 127.0.0.1:3306:3306 -e MYSQL_ROOT_PASSWORD=root mysql:8
      sudo apt update
      # Needed to improve performance in Symfony CLI
      sudo apt install -y php8.1-fpm
      # Install Symfony CLI + Shopware CLI
      brew install symfony-cli/tap/symfony-cli FriendsOfShopware/tap/shopware-cli
      composer install
      ./bin/console system:setup -n --database-url "mysql://root:root@127.0.0.1:3306/shopware" --app-url "$(gp url 8000)" --app-env dev
      # Setup Trusted Proxies
      echo "TRUSTED_PROXIES=192.168.0.0/16" >> .env
      composer run setup
    command: symfony serve --port=8000
  - name: Getting Started
    init: |
      echo 'alias admin-watch="APP_URL=http://localhost:8000 composer run watch:admin"' >> ~/.bashrc
    command: |
      echo 'Hey!. Your environment is starting soon. You can see the progress in the Shopware Terminal'
      echo 'If you want to run the Admin Watch, just use the Terminal alias: admin-watch'
      echo 'Happy Coding!'
ports:
  - name: Shopware
    port: 8000
    onOpen: notify
    description: Symfony Server
  - name: Admin-Watcher
    port: 8080
    onOpen: notify
    description: "Use Forward Proxy to localhost to access this service"

jetbrains:
  plugins:
    - com.jetbrains.php
    - com.intellij.php.tools.quality.phpstan
    - com.intellij.php.psalm
    - org.jetbrains.plugins.yaml
    - com.jetbrains.twig
    - de.espend.idea.php.annotation
    - fr.adrienbrault.idea.symfony2plugin
    - de.shyim.shopware6
    - de.shyim.ideaphpstantoolbox
