rest_routes:
  resource: Rest/Controller/
  type: annotation

administration_routes:
  resource: Administration/Controller/
  type: annotation

storefront_api_routes:
  resource: StorefrontApi/Controller/
  type: annotation