name: Lint Admin

on:
  push:
    branches:
      - trunk
  pull_request:
    paths:
      - src/Administration/Resources/app/administration/**/*

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

    steps:
      - name: Clone platform
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Setup
        run: |
          cd src/Administration/Resources/app/administration
          npm clean-install

      - name: Check Code
        run: |
          cd src/Administration/Resources/app/administration
          npm run lint
          npm run lint:types
          npm run lint:scss
